export const VALIDATE_ERROR = "输入完整且符合要求的内容"
export const ARTICLE_EMPTY = "一篇文章都没有 ~ 快去创作中心创作吧~"
export const NETWORK_ERROR = "网络出错了 稍后再试试吧~"
export const LOADINGING = "正在加载内容..."
export const CANSEL = '已取消该操作'
export const FORMAT_ERROR = '格式错误 只能选择png/jpg/jpeg格式的图片'
export const FILE_SIZE_ERROR = '文件大小不能超过2MB'
export const OPERATOR_OK = '操作成功'
export const OPERATOR_ERROR = '操作失败'